# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20191022_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='details',
            new_name='description',
        ),
    ]
