# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20191022_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
